### PR TITLE
GCC 12/13 compatibility fix

### LINKED ISSUE #1: crinit fails to build with gcc 13.2.1
Building crinit with the default setting of `ENABLE_WERROR` fails with recent gcc versions because a warning about a tautological condition is being promoted to an error:

```
/.../crinit/src/fseries.c: In function ‘crinitScanDirFilter’:
/.../crinit/src/fseries.c:261:38: error: the comparison will always evaluate as ‘false’ for the address of ‘d_name’ will never be NULL [-Werror=address]
  261 |     if (dent == NULL || dent->d_name == NULL) {
      |                                      ^~
In file included from /usr/include/dirent.h:61,
                 from /.../crinit/src/fseries.c:8:
/usr/include/bits/dirent.h:33:10: note: ‘d_name’ declared here
   33 |     char d_name[256];           /* We must not include limits.h! */
      |          ^~~~~~
cc1: all warnings being treated as errors
```

While `dent->d_name` decays into a `char*`, POSIX specifies that this is an embedded array in `struct dirent`, so this warning is actually sound and the redundant check could simply be removed.

### PR DESCRIPTION
**Pull request by gmcn42**
Closes #1 

Also added a commit making the Ubuntu release used by the build container configurable.

To test GCC 12 compatibility locally, we can now switch to Ubuntu 23.04 Lunar via
```
$ ci/docker-run.sh amd64 lunar
```
and then use `ci/build.sh` as normal.

### CODE REVIEW

**Review by ThomasBrinker — APPROVED** [review]
looks good
